# Dockerfile

ARG NODE_VERSION=22.12.0
FROM node:${NODE_VERSION}-slim as base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN npm install -g corepack@latest
RUN corepack enable

ARG PORT=3000
WORKDIR /src

# Build
FROM base as build

# Build-time environment variables (required for SSG prerendering)
ARG GQL_HOST
ARG APP_HOST
ARG NUXT_IMAGE_DOMAINS
ARG NUXT_PUBLIC_PRODUCTS_PER_PAGE
ARG NUXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG PRIMARY_COLOR
ARG NUXT_PUBLIC_WHATSAPP_PHONE
ARG NUXT_PUBLIC_SITE_NAME
ARG NUXT_PUBLIC_SITE_SHORT_DESCRIPTION
ARG NUXT_PUBLIC_SITE_DESCRIPTION
ARG NUXT_PUBLIC_SITE_IMAGE
ARG NUXT_PUBLIC_ORGANIZATION_LOGO
ARG NUXT_PUBLIC_ORGANIZATION_CONTACT_EMAIL
ARG NUXT_PUBLIC_ORGANIZATION_PHONE
ARG NUXT_PUBLIC_ORGANIZATION_ADDRESS
ARG NUXT_PUBLIC_ORGANIZATION_SOCIAL_FACEBOOK
ARG NUXT_PUBLIC_ORGANIZATION_SOCIAL_TWITTER
ARG NUXT_PUBLIC_ORGANIZATION_SOCIAL_INSTAGRAM
ARG NUXT_PUBLIC_GOOGLE_MAPS_EMBED
ARG NUXT_PUBLIC_CURRENCY_CODE
ARG NUXT_PUBLIC_FRONT_END_URL

# Set environment variables from build args
ENV GQL_HOST=$GQL_HOST
ENV APP_HOST=$APP_HOST
ENV NUXT_IMAGE_DOMAINS=$NUXT_IMAGE_DOMAINS
ENV NUXT_PUBLIC_PRODUCTS_PER_PAGE=$NUXT_PUBLIC_PRODUCTS_PER_PAGE
ENV NUXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NUXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV PRIMARY_COLOR=$PRIMARY_COLOR
ENV NUXT_PUBLIC_WHATSAPP_PHONE=$NUXT_PUBLIC_WHATSAPP_PHONE
ENV NUXT_PUBLIC_SITE_NAME=$NUXT_PUBLIC_SITE_NAME
ENV NUXT_PUBLIC_SITE_SHORT_DESCRIPTION=$NUXT_PUBLIC_SITE_SHORT_DESCRIPTION
ENV NUXT_PUBLIC_SITE_DESCRIPTION=$NUXT_PUBLIC_SITE_DESCRIPTION
ENV NUXT_PUBLIC_SITE_IMAGE=$NUXT_PUBLIC_SITE_IMAGE
ENV NUXT_PUBLIC_ORGANIZATION_LOGO=$NUXT_PUBLIC_ORGANIZATION_LOGO
ENV NUXT_PUBLIC_ORGANIZATION_CONTACT_EMAIL=$NUXT_PUBLIC_ORGANIZATION_CONTACT_EMAIL
ENV NUXT_PUBLIC_ORGANIZATION_PHONE=$NUXT_PUBLIC_ORGANIZATION_PHONE
ENV NUXT_PUBLIC_ORGANIZATION_ADDRESS=$NUXT_PUBLIC_ORGANIZATION_ADDRESS
ENV NUXT_PUBLIC_ORGANIZATION_SOCIAL_FACEBOOK=$NUXT_PUBLIC_ORGANIZATION_SOCIAL_FACEBOOK
ENV NUXT_PUBLIC_ORGANIZATION_SOCIAL_TWITTER=$NUXT_PUBLIC_ORGANIZATION_SOCIAL_TWITTER
ENV NUXT_PUBLIC_ORGANIZATION_SOCIAL_INSTAGRAM=$NUXT_PUBLIC_ORGANIZATION_SOCIAL_INSTAGRAM
ENV NUXT_PUBLIC_GOOGLE_MAPS_EMBED=$NUXT_PUBLIC_GOOGLE_MAPS_EMBED
ENV NUXT_PUBLIC_CURRENCY_CODE=$NUXT_PUBLIC_CURRENCY_CODE
ENV NUXT_PUBLIC_FRONT_END_URL=$NUXT_PUBLIC_FRONT_END_URL

COPY . .

# Ensure a clean install
RUN rm -rf node_modules

RUN pnpm install --frozen-lockfile
RUN npm install --platform=linux --arch=x64 sharp
# Ensure production mode during static generation so robots.txt and sitemap use prod rules
RUN NODE_ENV=production pnpm run generate

FROM nginx:alpine

ENV PORT=3000

# Copy the static files from build stage
COPY --from=build /src/.output/public /usr/share/nginx/html

# Copy nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Create a startup script to handle PORT environment variable
RUN echo '#!/bin/sh' > /docker-entrypoint.sh && \
    echo 'sed -i "s/listen 3000/listen $PORT/g" /etc/nginx/conf.d/default.conf' >> /docker-entrypoint.sh && \
    echo 'sed -i "s/listen \[::\]:3000/listen [::]:$PORT/g" /etc/nginx/conf.d/default.conf' >> /docker-entrypoint.sh && \
    echo 'exec nginx -g "daemon off;"' >> /docker-entrypoint.sh && \
    chmod +x /docker-entrypoint.sh

EXPOSE 3000

CMD ["/docker-entrypoint.sh"]